- Refactored some dockerfiles and switched to a new DECVM version - Refactored a few commands - Updated the table builder to be able to build multi line cells

diff --git a/MinecraftPlugin/Dockerfile b/MinecraftPlugin/Dockerfile
--- a/MinecraftPlugin/Dockerfile
+++ b/MinecraftPlugin/Dockerfile
@@ -1,28 +1,30 @@
-FROM openjdk:8-jre
+#FROM openjdk:8-jre-alpine
+FROM dcevm11
 
-# DCEVM part
-# Sources: https://github.com/dcevm/dcevm, http://hotswapagent.org/
+#### DCEVM part ###
+## Sources: https://github.com/dcevm/dcevm, http://hotswapagent.org/
+#
+#WORKDIR "/install"
+#
+##RUN apt-get update
+##RUN apk add curl gcompat
+#
+## Download DCEVM pach
+#RUN wget -O DCEVM_latest.jar $(curl -s https://api.github.com/repos/dcevm/dcevm/releases/latest \
+#            | grep browser_download_url \
+#            | cut -d '"' -f 4 \
+#            )
+#
+## Download hotswap-agent.jar
+#RUN wget -O hotswap-agent_latest.jar "https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-1.4.1.jar"
+#
+#RUN unzip DCEVM_latest.jar "linux_amd64_compiler2/product/libjvm.so"
+#
+#RUN mkdir "$JAVA_HOME/lib/amd64/dcevm" \
+#    && cp "linux_amd64_compiler2/product/libjvm.so" "$JAVA_HOME/lib/amd64/dcevm"
+#
 
-WORKDIR "/install"
-
-RUN apt-get update
-
-# Download DECM pach
-RUN wget -O DCEVM_latest.jar $(curl -s https://api.github.com/repos/dcevm/dcevm/releases/latest \
-            | grep browser_download_url \
-            | cut -d '"' -f 4 \
-            )
-
-# Download hotswap-agent.jar
-RUN wget -O hotswap-agent_latest.jar "https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.4.1/hotswap-agent-1.4.1.jar"
-
-RUN unzip DCEVM_latest.jar "linux_amd64_compiler2/product/libjvm.so"
-
-RUN mkdir "$JAVA_HOME/lib/amd64/dcevm" \
-    && cp "linux_amd64_compiler2/product/libjvm.so" "$JAVA_HOME/lib/amd64/dcevm"
-
-
-# PaperMC part
+### PaperMC part ###
 
 # This name is also used by the Website
 LABEL DockerMCType="Minecraft"
@@ -36,9 +38,11 @@ VOLUME [ "/server" ]
 
 ENV TASK_NAME "NO_TASK_NAME"
 
-HEALTHCHECK --interval=10s --start-period=10s --retries=2 --timeout=2s CMD curl -f http://localhost:8001/health || exit 1
+#HEALTHCHECK --interval=10s --start-period=20s --retries=2 --timeout=2s CMD curl -f http://localhost:8001/health || exit 1
 
 COPY docker/server /server
 COPY target/MinecraftPlugin-1.0.jar /server/plugins
 
-CMD ["java", "-Xmx20G", "-XXaltjvm=dcevm", "-javaagent:/install/hotswap-agent_latest.jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-jar", "papermc.jar" ]
+#CMD ["java", "-Xmx20G", "-XXaltjvm=dcevm", "-javaagent:/install/hotswap-agent_latest.jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-jar", "papermc.jar" ]
+CMD ["java", "-Xmx20G", "-XX:HotswapAgent=core", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-jar", "papermc.jar" ]
+#CMD ["java", "-Xmx2G", "-jar", "papermc.jar" ]
